name: Main

on: [push]

jobs:
    all:
        runs-on: ubuntu-latest

        steps:
             - uses: actions/checkout@v2
             - uses: actions/setup-node@v1
               with:
                node_version: "12.16"
             - name: Install dependencies
               run: yarn install
             - name: Compile contracts
               run: yarn hardhat compile
             - name: Run unit tests
               run: yarn hardhat test
             - name: Run Prettier
               run: yarn run prettier --check .

